# Generated by Django 5.0.6 on 2024-06-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbuploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='accounts',
        ),
    ]
